Target service option
bloomberg/powerfulseal pull request #354
Opened 2021-10-14 13:18 UTC by Aergonus

reopens #339 for hacktoberfest ;)

2021-10-21 11:06 UTC, seeker89 requested changes
I believe you have a typo - other than that looks useful :)

Thanks for the PR!

2021-10-21 11:06 UTC, seeker89 commented on powerfulseal/policy/action_clone.py
> +    body = [{"op": type, "path": "/spec/selector/chaos", "value": "true"}]
```suggestion
    body = [{"op": self.type, "path": "/spec/selector/chaos", "value": "true"}]
```

It looks like you're using an undefined variable here.

2021-10-21 11:06 UTC, seeker89 commented on powerfulseal/policy/ps-schema.yaml
> +          services:
This could have a little more informative name, like `servicesToMark` or something like that, so that it's easier to guess what this is for.

2021-10-21 11:06 UTC, seeker89 commented on powerfulseal/policy/action_clone.py
> +          ).execute()
Given the usage, it probably could have been a function, instead of a single-method class, but that's no biggie.

2021-10-21 11:42 UTC, Aergonus commented on powerfulseal/policy/ps-schema.yaml
> +          services:
`servicesToRetarget`?

2021-10-22 10:05 UTC, seeker89 approved these changes

2021-10-22 10:05 UTC, merged

2021-10-24 23:25 UTC, Aergonus commented
resolves https://github.com/powerfulseal/powerfulseal/issues/336